/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenHMD */

#ifndef _Included_OpenHMD
#define _Included_OpenHMD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenHMD
 * Method:    ohmd_ctx_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OpenHMD_ohmd_1ctx_1create
  (JNIEnv *, jclass);

/*
 * Class:     OpenHMD
 * Method:    ohmd_ctx_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OpenHMD_ohmd_1ctx_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     OpenHMD
 * Method:    ohmd_ctx_get_error
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OpenHMD_ohmd_1ctx_1get_1error
  (JNIEnv *, jclass, jlong);

/*
 * Class:     OpenHMD
 * Method:    ohmd_ctx_update
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OpenHMD_ohmd_1ctx_1update
  (JNIEnv *, jclass, jlong);

/*
 * Class:     OpenHMD
 * Method:    ohmd_ctx_probe
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_OpenHMD_ohmd_1ctx_1probe
  (JNIEnv *, jclass, jlong);

/*
 * Class:     OpenHMD
 * Method:    ohmd_list_gets
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OpenHMD_ohmd_1list_1gets
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     OpenHMD
 * Method:    ohmd_list_open_device
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_OpenHMD_ohmd_1list_1open_1device
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     OpenHMD
 * Method:    ohmd_close_device
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_OpenHMD_ohmd_1close_1device
  (JNIEnv *, jclass, jlong);

/*
 * Class:     OpenHMD
 * Method:    ohmd_device_getf
 * Signature: (JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_OpenHMD_ohmd_1device_1getf
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     OpenHMD
 * Method:    ohmd_device_setf
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_OpenHMD_ohmd_1device_1setf
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     OpenHMD
 * Method:    ohmd_device_geti
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_OpenHMD_ohmd_1device_1geti
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
